/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ACEVEDO
 */
public class vistaPatio2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaPatio2.class.getName());

    /**
     * Creates new form vistaPatio2
     */
    public vistaPatio2() {
        initComponents();
        jPanel1.setLayout(null);
        ImageIcon iconoPatio2=new ImageIcon(getClass().getResource("/imagen/Patio2.png"));
        Image imagenPatio2=iconoPatio2.getImage();
        Fondo.setIcon(new ImageIcon(imagenPatio2.getScaledInstance(Fondo.getWidth(), Fondo.getHeight(),Image.SCALE_SMOOTH)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnBarriga = new javax.swing.JButton();
        btnQuico = new javax.swing.JButton();
        btnProfesor = new javax.swing.JButton();
        btnFuente = new javax.swing.JButton();
        LabelLibre2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ComoboboxControlar = new javax.swing.JComboBox<>();
        btnInteractuar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 820, 40));

        btnBarriga.setOpaque(false);
        btnBarriga.setBackground(new java.awt.Color(0, 0, 0,0));
        btnBarriga.setBorderPainted(false);
        jPanel1.add(btnBarriga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 90, 150));

        btnQuico.setOpaque(false);
        btnQuico.setBackground(new java.awt.Color(0, 0, 0,0));
        btnQuico.setBorderPainted(false);
        jPanel1.add(btnQuico, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 60, 260));

        btnProfesor.setOpaque(false);
        btnProfesor.setBackground(new java.awt.Color(0,0, 0, 0));
        btnProfesor.setBorderPainted(false);
        jPanel1.add(btnProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 260));

        btnFuente.setOpaque(false);
        btnFuente.setBackground(new java.awt.Color(0, 0, 0,0));
        btnFuente.setBorderPainted(false);
        jPanel1.add(btnFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 120, 170));
        jPanel1.add(LabelLibre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 440, 290));

        Fondo.setBackground(new java.awt.Color(204, 204, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Patio2.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 850, 530));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("¿A quien quieres controlar?"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComoboboxControlar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chavo", "Chilindrina", "Doña_Florinda", "Don_Ramon", "Señor_Barriga", "Quico", "Profesor" }));
        jPanel2.add(ComoboboxControlar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 230, 90));

        btnInteractuar.setText("Interactuar");
        getContentPane().add(btnInteractuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 220, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Area de texto"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 23, 210, 320));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 230, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaPatio2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea AreaTexto;
    public javax.swing.JComboBox<String> ComoboboxControlar;
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel LabelLibre2;
    public javax.swing.JButton btnBarriga;
    public javax.swing.JButton btnFuente;
    public javax.swing.JButton btnInteractuar;
    public javax.swing.JButton btnProfesor;
    public javax.swing.JButton btnQuico;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
