/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ACEVEDO
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        Panel1.setLayout(null);
        ImageIcon iconoLobo=new ImageIcon(getClass().getResource("/imagen/Lobo.png"));
        ImageIcon icono=new ImageIcon(getClass().getResource("/imagen/Abuelita.png"));
        ImageIcon iconoCaperucita =new ImageIcon(getClass().getResource("/imagen/Caperucita.png"));
        ImageIcon iconoLeñador=new ImageIcon(getClass().getResource("/imagen/Leñador.png"));
        
        Image imagenLobo=iconoLobo.getImage();
        Image imagenCaperucita=iconoCaperucita.getImage();
        Image imagen=icono.getImage();
        Image imagenLeñador=iconoLeñador.getImage();
        
        Image ajustarLeñador=imagenLeñador.getScaledInstance(Label5Leñador.getWidth(), Label5Leñador.getHeight(), Image.SCALE_SMOOTH);
        Image ajustarLobo=imagenLobo.getScaledInstance(Label4Lobo.getWidth(), Label4Lobo.getHeight(), Image.SCALE_SMOOTH);
        Image ajustada=imagen.getScaledInstance(jLabel2Abuelita.getWidth(), jLabel2Abuelita.getHeight(), Image.SCALE_SMOOTH);
        Image ajustadaCaperucita=imagenCaperucita.getScaledInstance(jLabel3Caper.getWidth(), jLabel3Caper.getHeight(), Image.SCALE_SMOOTH);
        jLabel3Caper.setIcon(new ImageIcon(ajustadaCaperucita));
        jLabel2Abuelita.setIcon(new ImageIcon(ajustada));
        Label4Lobo.setIcon(new ImageIcon(ajustarLobo));
        Label5Leñador.setIcon(new ImageIcon(ajustarLeñador));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2Abuelita = new javax.swing.JLabel();
        jLabel3Caper = new javax.swing.JLabel();
        Label4Lobo = new javax.swing.JLabel();
        Label5Leñador = new javax.swing.JLabel();
        btnEvento = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        ComboCaperucita = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboAbuela = new javax.swing.JComboBox<>();
        ComboLeñador = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboLobo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea1Caperucita = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextAreaLobo = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextAreaAbuelita = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextAreaLeñador = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(255, 204, 204));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Casa.png"))); // NOI18N
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 98, -1));

        jLabel2Abuelita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Abuelita.png"))); // NOI18N
        Panel1.add(jLabel2Abuelita, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 35, 87, 93));

        jLabel3Caper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Caperucita.png"))); // NOI18N
        Panel1.add(jLabel3Caper, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 420, 87, 92));

        Label4Lobo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Lobo.png"))); // NOI18N
        Panel1.add(Label4Lobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 418, 87, 94));

        Label5Leñador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Leñador.png"))); // NOI18N
        Panel1.add(Label5Leñador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 87, 89));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 6, 550, 530));

        btnEvento.setText("Siguiente");
        getContentPane().add(btnEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 455, 100, 73));

        btnReiniciar.setText("Reiniciar");
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 455, 100, 73));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Area de Texto"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, 252, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 270, 389));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboCaperucita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantar", "Bailar", "Mirar_Facebook" }));
        jPanel2.add(ComboCaperucita, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 18, 130, -1));

        jLabel3.setText("Caperucita");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 21, -1, -1));

        jLabel6.setText("Abuela");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 105, -1, -1));

        ComboAbuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gritar", "Ofrecer_cafe", "Estudiar_POO", "Cambiarse_ropa" }));
        jPanel2.add(ComboAbuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 102, 130, -1));

        ComboLeñador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salvar", "Abrir_Panza", "Rellenar_Panza", "Regalar_dulce" }));
        jPanel2.add(ComboLeñador, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 74, 130, -1));

        jLabel5.setText("Leñador");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 77, -1, -1));

        ComboLobo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correr", "Tragar_Abuelita", "Tragar_Caperucita", "Disfrazarse" }));
        jPanel2.add(ComboLobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 46, -1, -1));

        jLabel4.setText("Lobo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 49, 37, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 260, 140));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Caperucita"));

        TextArea1Caperucita.setColumns(20);
        TextArea1Caperucita.setRows(5);
        jScrollPane2.setViewportView(TextArea1Caperucita);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 6, 224, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lobo"));

        TextAreaLobo.setColumns(20);
        TextAreaLobo.setRows(5);
        jScrollPane4.setViewportView(TextAreaLobo);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 115, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Abuelita"));

        TextAreaAbuelita.setColumns(20);
        TextAreaAbuelita.setRows(5);
        jScrollPane6.setViewportView(TextAreaAbuelita);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 339, -1, -1));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Leñador"));

        TextAreaLeñador.setColumns(20);
        TextAreaLeñador.setRows(5);
        jScrollPane5.setViewportView(TextAreaLeñador);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 224, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboAbuela;
    public javax.swing.JComboBox<String> ComboCaperucita;
    public javax.swing.JComboBox<String> ComboLeñador;
    public javax.swing.JComboBox<String> ComboLobo;
    public javax.swing.JLabel Label4Lobo;
    public javax.swing.JLabel Label5Leñador;
    public javax.swing.JPanel Panel1;
    public javax.swing.JTextArea TextArea1;
    public javax.swing.JTextArea TextArea1Caperucita;
    public javax.swing.JTextArea TextAreaAbuelita;
    public javax.swing.JTextArea TextAreaLeñador;
    public javax.swing.JTextArea TextAreaLobo;
    public javax.swing.JButton btnEvento;
    public javax.swing.JButton btnReiniciar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2Abuelita;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel3Caper;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables


    class FondoPanel extends JPanel {
 
        private Image imagen;
 
        public FondoPanel() { 
            setOpaque(false);
        }
 
        @Override
        protected void paintComponent(Graphics e) {
            super.paintComponent(e);
            if (imagen == null) {
                imagen = new ImageIcon(
                    getClass().getResource("/imagen/Bosque.png")
                ).getImage();
            }
             e.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
    
    
    
    
    
    
}
