/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author memoy
 */
public class JFJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFJuego.class.getName());

    /**
     * Creates new form JFJuego
     */
    public JFJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNivelDano = new javax.swing.JLabel();
        lblPotenciadorDano = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblVidaAres = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnEnemigo = new javax.swing.JButton();
        btnMultiplicador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAtacarAres = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEscudo = new javax.swing.JButton();
        btnLazo = new javax.swing.JButton();
        btnInteractuar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Juego Wonder Woman"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Steve.png")).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 100, 100));

        lblNivelDano.setForeground(new java.awt.Color(0, 0, 0));
        lblNivelDano.setText("Nivel de Daño: 0");
        jPanel1.add(lblNivelDano, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 133, -1));

        lblPotenciadorDano.setForeground(new java.awt.Color(0, 0, 0));
        lblPotenciadorDano.setText("Potenciador de Daño:  0/500");
        jPanel1.add(lblPotenciadorDano, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ares.png")).getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 91, 200, 200));

        lblVidaAres.setForeground(new java.awt.Color(0, 0, 0));
        lblVidaAres.setText("Puntos de vida: 500/500");
        jPanel1.add(lblVidaAres, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 69, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Goomba.png")).getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 200, 200));

        btnEnemigo.setText("Eliminar Enemigo");
        btnEnemigo.addActionListener(this::btnEnemigoActionPerformed);
        jPanel1.add(btnEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 309, -1, -1));

        btnMultiplicador.setText("Potenciar Daño");
        btnMultiplicador.addActionListener(this::btnMultiplicadorActionPerformed);
        jPanel1.add(btnMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Habilidades/Objetos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wonder Woman.png")).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, 100));

        btnAtacarAres.setText("Atacar");
        btnAtacarAres.addActionListener(this::btnAtacarAresActionPerformed);
        jPanel1.add(btnAtacarAres, new org.netbeans.lib.awtextra.AbsoluteConstraints(1113, 309, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wonder Woman.png")).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, 100));

        btnEscudo.setText("Usar Escudo");
        btnEscudo.addActionListener(this::btnEscudoActionPerformed);
        jPanel1.add(btnEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        btnLazo.setText("Usar Lazo");
        jPanel1.add(btnLazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        btnInteractuar.setText("Interactuar");
        jPanel1.add(btnInteractuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Themyscira.png")).getImage().getScaledInstance(1440, 440, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnemigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnemigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnemigoActionPerformed

    private void btnMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicadorActionPerformed

    private void btnAtacarAresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarAresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtacarAresActionPerformed

    private void btnEscudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtacarAres;
    public javax.swing.JButton btnEnemigo;
    public javax.swing.JButton btnEscudo;
    public javax.swing.JButton btnInteractuar;
    public javax.swing.JButton btnLazo;
    public javax.swing.JButton btnMultiplicador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblNivelDano;
    public javax.swing.JLabel lblPotenciadorDano;
    public javax.swing.JLabel lblVidaAres;
    // End of variables declaration//GEN-END:variables
}
